# ✅ AWS AUTO RESIZE
- name: Increase EBS Volume (AWS)
  amazon.aws.ec2_vol:
    id: vol-0b257fa0954efa050
    region: us-east-1
    volume_size: 25
    state: present
  delegate_to: localhost
  become: false


# ✅ OS EXPAND
- name: Expand partition
  command: growpart /dev/nvme0n1 1
  become: yes
  failed_when: false

- name: Resize filesystem
  command: resize2fs /dev/nvme0n1p1
  become: yes


# ✅ GET CR
- name: Get Change Request sys_id
  uri:
    url: "https://nowlearning-nlinst04253758-14pkn-0001.lab.service-now.com/api/now/table/change_request?sysparm_query=short_description=EBS%20Volume%20Expansion^state=implement&sysparm_limit=1"
    method: GET
    user: admin
    password: 9MpTfxSWeVEe
    headers:
      Content-Type: "application/json"
    return_content: yes
  register: cr_response


# ✅ UPDATE CR
- name: Update ServiceNow Change Request
  uri:
    url: "https://nowlearning-nlinst04253758-14pkn-0001.lab.service-now.com/api/now/table/change_request/{{ cr_response.json.result[0].sys_id }}"
    method: PATCH
    user: admin
    password: 9MpTfxSWeVEe
    headers:
      Content-Type: "application/json"
    body:
      work_notes: "AWS + OS disk expansion completed ✅"
    body_format: json
