- name: Expand partition
  command: growpart /dev/nvme0n1 1
  failed_when: false

- name: Resize filesystem
  command: resize2fs /dev/nvme0n1p1

- name: Update ServiceNow Change Request to Resolved
  uri:
    url: "https://nowlearning-nlinst04253758-14pkn-0001.lab.service-now.com/api/now/table/change_request/eb5ed2cdac5103107f44cfa557089815"
    method: PATCH
    user: admin
    password: 9MpTfxSWeVEe
    headers:
      Content-Type: "application/json"
    body:
      state: "3"
      close_notes: "Resolved automatically via AAP automation"
    body_format: json
