- name: Expand partition
  command: growpart /dev/nvme0n1 1
  failed_when: false

- name: Resize filesystem
  command: resize2fs /dev/nvme0n1p1


# ✅ STEP 1 — Get CR sys_id dynamically (FIXED URL ✅)
- name: Get Change Request sys_id
  uri:
    url: "https://nowlearning-nlinst04253758-14pkn-0001.lab.service-now.com/api/now/table/change_request?sysparm_query=short_description=EBS%20Volume%20Expansion&sysparm_limit=1"
    method: GET
    user: admin
    password: 9MpTfxSWeVEe
    headers:
      Content-Type: "application/json"
    return_content: yes
  register: cr_response


# ✅ STEP 2 — Update same CR dynamically
- name: Update ServiceNow Change Request
  uri:
    url: "https://nowlearning-nlinst04253758-14pkn-0001.lab.service-now.com/api/now/table/change_request/{{ cr_response.json.result[0].sys_id }}"
    method: PATCH
    user: admin
    password: 9MpTfxSWeVEe
    headers:
      Content-Type: "application/json"
    body:
      work_notes: "Disk expansion completed via AAP automation ✅"
    body_format: json
